# Generated by Django 4.2.3 on 2023-07-20 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.animal'),
        ),
        migrations.AddConstraint(
            model_name='weighting',
            constraint=models.UniqueConstraint(fields=('animal', 'date'), name='one weighting per day'),
        ),
    ]
