# Generated by Django 4.2.3 on 2023-07-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_animal_parent_weighting_one_weighting_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='arrival_date',
            field=models.DateField(auto_created=True),
        ),
    ]
